name: mani_auth_plugin
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: any #^12.1.3
  mani_uikit:
    # path: ../mani_uikit
    git:
      url: http://gitlab.yagona.io/mobile/mani-uikit.git
      ref: develop

  myid_wrapper:
    git:
      url: https://github.com/sudo-ulmas/myid_wrapper.git
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.0
  intl: any
  provider: ^6.1.2



dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  # very_good_analysis: ^6.0.0

flutter:
  generate: true
